services:
  filego:
    build: .
    image: filego
    container_name: filego
    restart: always
    tty: true
    ports:
      - "7001:7001"
    environment:
      - MYSQL_HOST=dbhost
    volumes:
      - .:/usr/src/myapp
    command: "sh dev.sh"
